---
name: Repo Linter

on: [push, pull_request]

jobs:
  yaml_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Get file changes
        id: get_file_changes
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo file changes
        run: |
          echo Changed files: ${{ join(steps.get_file_changes.outputs.all, ' ') }}

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v1.0.0
        with:
          # Path to custom configuration
          config_file: .github/workflow-config/yamllint.yml
          # Path of changed files
          file_or_dir: ${{ join(fromJson(steps.get_file_changes.outputs.all), ' ') }}
          # Custom configuration (as YAML source)
          # config_data: # optional
          # Format for parsing output [parsable,standard,colored,auto]
          # format: # optional, default is colored
          # Return non-zero exit code on warnings as well as errors
          # strict: # optional, default is false
